
{
    "name": "AAA Skills Management",
    "summary": "Manage your employee skills",
    "version": "12.0.1.1",
    "category": "Human Resources",
    'website': 'https://www.auguria.fr',
    "author": "Auguria SAS",
    "depends": [
        "hr",
        "contacts",
        "project",
        "crm",
        "sale_timesheet",
        "sale_margin",
        "sale",
    ],
    'data': [
        
        "security/ir.model.access.csv",
        "views/hr_skill_level.xml",
        "views/hr_skill.xml",
        "views/res_partner.xml",
        "views/hr_skill_partner.xml",
        "views/hr_skill_search.xml",
        "views/crm_lead.xml",
        "views/crm_team.xml",
        "views/project_project.xml",
        "views/project_task.xml",
        "views/res_company.xml",
        "views/res_users.xml",
        "views/sale_order_line.xml",
        "data/email_templates.xml",
        #"views/hr_employee_skill.xml",
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
